# Generated by Django 5.1.4 on 2025-02-01 11:28
from django.db import migrations, models
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_alter_commande_user'),
    ]

    operations = [
         migrations.AddField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(null=True, blank=True, on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
