# Generated by Django 5.1.4 on 2025-02-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_remove_commande_nom_remove_commande_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
