# Generated by Django 5.1.4 on 2025-02-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_commande_adresse_commande_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('Express', 'Normale')], default='Normale', max_length=10),
        ),
    ]
