# Generated by Django 5.1 on 2025-02-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0006_commande_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='status',
        ),
        migrations.AddField(
            model_name='commande',
            name='statu',
            field=models.CharField(choices=[('Normale', 'Normale'), ('Express', 'Express')], default='Normale', max_length=10),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
