# Generated by Django 5.1.4 on 2025-01-16 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('En Attente', 'En Attente'), ('En Cours', 'En Cours'), ('Livrée', 'Livrée'), ('Échouée', 'Échouée')], default='En Attente', max_length=10)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livraison.livreur')),
            ],
        ),
    ]
