# Generated by Django 5.1.4 on 2025-01-16 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0002_livraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_at_time', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraison.livraison')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraison.livreur')),
            ],
        ),
    ]
