# Generated by Django 5.1.4 on 2025-01-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0004_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livreur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
