# Generated by Django 5.1 on 2025-01-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0006_utilisateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
