# Generated by Django 5.1.4 on 2025-02-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0007_delete_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='nom',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
