# Generated by Django 5.1.4 on 2025-02-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0008_livreur_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livreur',
            name='user',
        ),
    ]
